// Writes ../THIRD_PARTY_LICENSES.md from what esbuild actually put into the bundle (metafile), plus the build tools.
// Run: npm run licenses   (needs node_modules; reads package.json files and LICENSE files, no network)
import { existsSync } from 'node:fs'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { bundle } from '../build.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const modules = join(root, 'node_modules')
const outFile = resolve(root, '../THIRD_PARTY_LICENSES.md')

const own = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))
const { metafile } = await bundle()

// package directories that contributed at least one byte to the output
const shipped = new Set()
for (const out of Object.values(metafile.outputs)) {
  for (const [file, v] of Object.entries(out.inputs)) {
    if (!v.bytesInOutput) continue
    const i = file.lastIndexOf('node_modules/')
    if (i < 0) continue
    const rest = file.slice(i + 'node_modules/'.length).split('/')
    shipped.add(file.slice(0, i + 'node_modules/'.length) + (rest[0].startsWith('@') ? rest.slice(0, 2) : rest.slice(0, 1)).join('/'))
  }
}
const buildTools = ['esbuild', '@esbuild/darwin-arm64', '@esbuild/darwin-x64'].map((n) => join('node_modules', n)).filter((d) => existsSync(join(root, d)))

async function describe(dir, isShipped) {
  const abs = join(root, dir)
  const pkg = JSON.parse(await readFile(join(abs, 'package.json'), 'utf8'))
  const names = (await readdir(abs)).filter((f) => /^(licen[sc]e|copying|notice)/i.test(f))
  let text = ''
  for (const f of names) text += (text ? '\n\n' : '') + (await readFile(join(abs, f), 'utf8')).trim()
  const lic = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type || (pkg.licenses || []).map((l) => l.type).join(' OR ') || 'UNKNOWN'
  const repo = (typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url || '')
    .replace(/^git\+/, '').replace(/^git:\/\//, 'https://').replace(/\.git$/, '').replace(/^github:/, 'https://github.com/')
  const url = pkg.homepage || (repo.startsWith('http') ? repo : `https://www.npmjs.com/package/${pkg.name}`)
  const copyright = [...text.matchAll(/^.*copyright.*$/gim)].map((m) => m[0].trim()).slice(0, 2).join(' / ')
  return { name: pkg.name, version: pkg.version, license: lic, url, text, copyright, shipped: isShipped }
}

const shippedPkgs = await Promise.all([...shipped].map((d) => describe(d, true)))
const toolPkgs = await Promise.all(buildTools.map((d) => describe(d, false)))
const byName = (a, b) => a.name.localeCompare(b.name)
shippedPkgs.sort(byName)

const direct = [...Object.entries(own.dependencies || {}), ...Object.entries(own.devDependencies || {})]
const permissive = /^(MIT|ISC|BSD-2-Clause|BSD-3-Clause|Apache-2\.0|0BSD|BlueOak-1\.0\.0|Unlicense|CC0-1\.0|Python-2\.0|MIT-0)$/
// "A OR B": the user picks; it is fine when at least one alternative is permissive (we use that one, unmodified).
const alternatives = (p) => p.license.replace(/^\(|\)$/g, '').split(/\s+OR\s+/).map((a) => a.trim())
const flagged = shippedPkgs.filter((p) => !alternatives(p).some((a) => permissive.test(a)))
const dual = shippedPkgs.filter((p) => alternatives(p).length > 1 && !flagged.includes(p))

const row = (p) => `| ${p.name} | ${p.version} | ${p.license} | ${p.url} |`
const groups = new Map()
for (const p of shippedPkgs) {
  const key = (p.text || `(no licence file; package.json says ${p.license})`).replace(/\s+/g, ' ')
  if (!groups.has(key)) groups.set(key, { text: p.text, pkgs: [] })
  groups.get(key).pkgs.push(p.name)
}

const md = `# Third-party licences

Gloamlog itself is MIT (see \`LICENSE\`). The Notion-style editor in \`app/Resources/editor/index.html\` is a bundle of the
open-source packages below, built from \`editor-web/\` with esbuild. Only packages that put code into the bundle are listed
as shipped; this file is generated by \`npm run licenses\` in \`editor-web/\` from the real bundle, do not edit it by hand.

The editor makes no network request and embeds no font, script or image from anywhere else.

## Direct dependencies (editor-web/package.json, exact versions)

| Package | Version | Role |
|---|---|---|
${direct.map(([n, v]) => `| ${n} | ${v} | ${(own.devDependencies || {})[n] ? 'build tool, not shipped' : 'bundled into the editor'} |`).join('\n')}

Milkdown Crepe (MIT) is the editor; @milkdown/kit is the Milkdown toolkit it is built on (the same version Crepe pins).
LaTeX/KaTeX, the AI feature and the top bar of Crepe are not used and not bundled.

## Packages bundled into the editor (${shippedPkgs.length})

| Package | Version | Licence | URL |
|---|---|---|---|
${shippedPkgs.map(row).join('\n')}

${flagged.length ? `**Non-permissive or unrecognised licence ids: ${flagged.map((p) => `${p.name} (${p.license})`).join(', ')}**\n` : 'Every bundled package is under a permissive licence (MIT, ISC, BSD, Apache-2.0 or similar). No GPL, AGPL, SSPL or unknown licence.\n'}
${dual.map((p) => `${p.name} is dual-licensed (${p.license.replace(/^\(|\)$/g, '')}). Gloamlog uses it under ${alternatives(p).find((a) => permissive.test(a))}, unmodified, as an npm dependency.`).join('\n')}

## Build tools (used to build, not shipped)

| Package | Version | Licence | URL |
|---|---|---|---|
${toolPkgs.map(row).join('\n')}

## Licence texts

Each text below is copied verbatim from the package; packages with an identical text share one entry.

${[...groups.values()]
  .sort((a, b) => a.pkgs[0].localeCompare(b.pkgs[0]))
  .map((g) => `### ${g.pkgs.join(', ')}\n\n${g.text ? '```text\n' + g.text + '\n```' : '(the package ships no licence file; its package.json declares the licence listed in the table above)'}\n`)
  .join('\n')}
## Build tool licence texts

${toolPkgs.map((p) => `### ${p.name}\n\n${p.text ? '```text\n' + p.text + '\n```' : '(none shipped)'}\n`).join('\n')}`

await writeFile(outFile, md)
console.log(`wrote ${outFile}: ${shippedPkgs.length} bundled packages, ${groups.size} distinct licence texts, ${flagged.length} flagged`)
for (const p of flagged) console.log(`  FLAGGED ${p.name}@${p.version} ${p.license}`)
const counts = {}
for (const p of shippedPkgs) counts[p.license] = (counts[p.license] || 0) + 1
console.log('  licences:', JSON.stringify(counts))
